/**
 * Google Calendar Integration
 * 
 * Handles OAuth2 authentication and API interactions with Google Calendar.
 * This module provides functions to authenticate, fetch events, and monitor calendar changes.
 */

import { google } from 'googleapis';
import { EventType } from '@/lib/types';
import { env } from '@/lib/config/env';

/**
 * OAuth2 client configuration
 * Uses environment variables from centralized config
 */
function getOAuth2Client() {
  const clientId = env.google.clientId;
  const clientSecret = env.google.clientSecret;
  const redirectUri = env.google.redirectUri;

  if (!clientId || !clientSecret) {
    throw new Error('Google Calendar credentials not configured. Please set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET');
  }

  return new google.auth.OAuth2(clientId, clientSecret, redirectUri);
}

/**
 * Get authenticated calendar client
 * @param accessToken - OAuth2 access token
 * @param refreshToken - OAuth2 refresh token (optional)
 */
export function getCalendarClient(accessToken: string, refreshToken?: string) {
  const auth = getOAuth2Client();
  auth.setCredentials({
    access_token: accessToken,
    refresh_token: refreshToken,
  });

  return google.calendar({ version: 'v3', auth });
}

/**
 * Get authorization URL for OAuth2 flow
 * @param scopes - Array of Google API scopes
 */
export function getAuthUrl(scopes: string[] = [
  'https://www.googleapis.com/auth/calendar.readonly',
  'https://www.googleapis.com/auth/calendar.events',
]) {
  const oauth2Client = getOAuth2Client();
  return oauth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: scopes,
    prompt: 'consent',
  });
}

/**
 * Exchange authorization code for tokens
 * @param code - Authorization code from OAuth2 callback
 */
export async function getTokensFromCode(code: string) {
  const oauth2Client = getOAuth2Client();
  const { tokens } = await oauth2Client.getToken(code);
  return tokens;
}

/**
 * Refresh access token using refresh token
 * @param refreshToken - OAuth2 refresh token
 */
export async function refreshAccessToken(refreshToken: string) {
  const oauth2Client = getOAuth2Client();
  oauth2Client.setCredentials({ refresh_token: refreshToken });
  const { credentials } = await oauth2Client.refreshAccessToken();
  return credentials;
}

/**
 * Fetch events from Google Calendar
 * @param calendarClient - Authenticated calendar client
 * @param timeMin - Start time for events (default: now)
 * @param timeMax - End time for events (default: 30 days from now)
 * @param maxResults - Maximum number of events to return
 */
export async function fetchCalendarEvents(
  calendarClient: ReturnType<typeof getCalendarClient>,
  timeMin?: Date,
  timeMax?: Date,
  maxResults: number = 50
) {
  const now = new Date();
  const defaultTimeMax = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000); // 30 days from now

  console.log('[Google Calendar] Fetching events from primary calendar...');
  console.log(`[Google Calendar] Time range: ${timeMin?.toISOString() || now.toISOString()} to ${timeMax?.toISOString() || defaultTimeMax.toISOString()}`);

  const response = await calendarClient.events.list({
    calendarId: 'primary',
    timeMin: timeMin?.toISOString() || now.toISOString(),
    timeMax: timeMax?.toISOString() || defaultTimeMax.toISOString(),
    maxResults,
    singleEvents: true,
    orderBy: 'startTime',
  });

  const events = response.data.items || [];
  console.log(`[Google Calendar] Received ${events.length} events from API`);
  
  if (events.length > 0) {
    events.forEach((event, index) => {
      console.log(`[Google Calendar] Event ${index + 1}:`, {
        id: event.id,
        title: event.summary,
        start: event.start?.dateTime || event.start?.date,
        location: event.location,
      });
    });
  }

  return events;
}

/**
 * Convert Google Calendar event to our EventType format
 * @param googleEvent - Google Calendar API event object
 */
export function convertGoogleEventToEventType(googleEvent: any): Partial<EventType> {
  const startDate = googleEvent.start?.dateTime 
    ? new Date(googleEvent.start.dateTime)
    : googleEvent.start?.date 
    ? new Date(googleEvent.start.date)
    : new Date();

  return {
    id: googleEvent.id || '',
    title: googleEvent.summary || 'Untitled Event',
    date: startDate,
    location: googleEvent.location,
    participants: googleEvent.attendees?.map((a: any) => a.email || a.displayName) || [],
    status: 'pending',
    tasks: [], // Tasks will be generated by AI analyzer
  };
}

/**
 * Create a new calendar event
 * @param calendarClient - Authenticated calendar client
 * @param eventData - Event data to create
 */
export async function createCalendarEvent(
  calendarClient: ReturnType<typeof getCalendarClient>,
  eventData: {
    summary: string;
    description?: string;
    start: { dateTime?: string; date?: string };
    end: { dateTime?: string; date?: string };
    location?: string;
    attendees?: Array<{ email: string }>;
  }
) {
  const response = await calendarClient.events.insert({
    calendarId: 'primary',
    requestBody: eventData,
  });

  return response.data;
}

/**
 * Create a watch subscription for calendar events (webhooks)
 * @param calendarClient - Authenticated calendar client
 * @param webhookUrl - Public URL where Google will send webhook notifications
 * @param channelId - Unique channel ID for this subscription
 */
export async function createWatchSubscription(
  calendarClient: ReturnType<typeof getCalendarClient>,
  webhookUrl: string,
  channelId?: string
) {
  const uniqueChannelId = channelId || `channel-${Date.now()}-${Math.random().toString(36).substring(7)}`;
  
  console.log('[Google Calendar] Creating watch subscription...');
  console.log(`[Google Calendar] Channel ID: ${uniqueChannelId}`);
  console.log(`[Google Calendar] Webhook URL: ${webhookUrl}`);

  const response = await calendarClient.events.watch({
    calendarId: 'primary',
    requestBody: {
      id: uniqueChannelId,
      type: 'webhook',
      address: webhookUrl,
    },
  });

  console.log('[Google Calendar] ✅ Watch subscription created successfully');
  console.log(`[Google Calendar] Resource ID: ${response.data.resourceId}`);
  console.log(`[Google Calendar] Expiration: ${response.data.expiration}`);

  return {
    channelId: uniqueChannelId,
    resourceId: response.data.resourceId,
    expiration: response.data.expiration,
  };
}

/**
 * Stop a watch subscription
 * @param calendarClient - Authenticated calendar client
 * @param resourceId - Resource ID from the watch subscription
 * @param channelId - Channel ID from the watch subscription
 */
export async function stopWatchSubscription(
  calendarClient: ReturnType<typeof getCalendarClient>,
  resourceId: string,
  channelId: string
) {
  console.log('[Google Calendar] Stopping watch subscription...');
  console.log(`[Google Calendar] Resource ID: ${resourceId}`);
  console.log(`[Google Calendar] Channel ID: ${channelId}`);

  await calendarClient.channels.stop({
    requestBody: {
      id: channelId,
      resourceId: resourceId,
    },
  });

  console.log('[Google Calendar] ✅ Watch subscription stopped');
}

